---
language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
    - .jest
before_script:
  - sudo sysctl fs.inotify.max_user_watches=524288
  - sudo sysctl fs.inotify.max_queued_events=524288
  - sudo sysctl -p
  - npm install -g npm@latest
  - npm install -g expo-cli
script:
  - npm ci
  - npx jest --ci
jobs:
  include:
    - stage: deploy
      node_js: lts/*
      script:
        - npm ci
        # - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        # - npx expo publish --non-interactive