export const PRODUCTS_FETCH_STARTED = 'PRODUCTS_FETCH_STARTED';
export const PRODUCTS_FETCH_COMPLETED = 'PRODUCTS_FETCH_COMPLETED';
export const PRODUCTS_FETCH_FAILED = 'PRODUCTS_FETCH_FAILED';

export const PRODUCT_ADD_STARTED = 'PRODUCT_ADD_STARTED';
export const PRODUCT_ADD_COMPLETED = 'PRODUCT_ADD_COMPLETED';
export const PRODUCT_ADD_FAILED = 'PRODUCT_ADD_FAILED';

export const PRODUCT_EDIT_STARTED = 'PRODUCT_EDIT_STARTED';
export const PRODUCT_EDIT_COMPLETED = 'PRODUCT_EDIT_COMPLETED';
export const PRODUCT_EDIT_FAILED = 'PRODUCT_EDIT_FAILED';

export const PRODUCT_REMOVE_STARTED = 'PRODUCT_REMOVE_STARTED';
export const PRODUCT_REMOVE_COMPLETED = 'PRODUCT_REMOVE_COMPLETED';
export const PRODUCT_REMOVE_FAILED = 'PRODUCT_REMOVE_FAILED';

export const PRODUCT_SELECTED = 'PRODUCT_SELECTED';
export const PRODUCT_DESELECTED = 'PRODUCT_DESELECTED';

export const PRODUCT_ADD_TO_ORDER = 'PRODUCT_ADD_TO_ORDER';
export const PRODUCT_DELETE_TO_ORDER = 'PRODUCT_DELETE_TO_ORDER';

export const PRODUCT_INGREDIENT_ADD_STARTED = 'PRODUCT_INGREDIENT_ADD_STARTED';
export const PRODUCT_INGREDIENT_ADD_COMPLETED = 'PRODUCT_INGREDIENT_ADD_COMPLETED';
export const PRODUCT_INGREDIENT_ADD_FAILED = 'PRODUCT_INGREDIENT_ADD_FAILED';

export const PRODUCT_INGREDIENT_EDIT_STARTED = 'PRODUCT_INGREDIENT_EDIT_STARTED';
export const PRODUCT_INGREDIENT_EDIT_COMPLETED = 'PRODUCT_INGREDIENT_EDIT_COMPLETED';
export const PRODUCT_INGREDIENT_EDIT_FAILED = 'PRODUCT_INGREDIENT_EDIT_FAILED';

export const PRODUCT_INGREDIENT_SAVED = 'PRODUCT_INGREDIENT_SAVED';
export const PRODUCT_INGREDIENT_EDITED = 'PRODUCT_INGREDIENT_EDITED';
export const PRODUCT_INGREDIENTS_CLEARED = 'PRODUCT_INGREDIENTS_CLEARED';

export const PRODUCT_ADDITIONAL_SAVED = 'PRODUCT_ADDITIONAL_SAVED';
export const PRODUCT_ADDITIONAL_EDITED = 'PRODUCT_ADDITIONAL_EDITED';
export const PRODUCT_ADDITIONALS_CLEARED = 'PRODUCT_ADDITIONALS_CLEARED';


export const PRODUCT_SEARCH_STARTED = 'PRODUCT_SEARCH_STARTED';