export const FETCH_SALES_REPORT_BY_DATE_STARTED = 'FETCH_SALES_REPORT_BY_DATE_STARTED';
export const FETCH_SALES_REPORT_BY_DATE_COMPLETED = 'FETCH_SALES_REPORT_BY_DATE_COMPLETED';
export const FETCH_SALES_REPORT_BY_DATE_FAILED = 'FETCH_SALES_REPORT_BY_DATE_FAILED';

export const FETCH_SALES_REPORT_BY_BRANCH_STARTED = 'FETCH_SALES_REPORT_BY_BRANCH_STARTED';
export const FETCH_SALES_REPORT_BY_BRANCH_COMPLETED = 'FETCH_SALES_REPORT_BY_BRANCH_COMPLETED';
export const FETCH_SALES_REPORT_BY_BRANCH_FAILED = 'FETCH_SALES_REPORT_BY_BRANCH_FAILED';

export const FETCH_SALES_REPORT_BY_USER_STARTED = 'FETCH_SALES_REPORT_BY_USER_STARTED';
export const FETCH_SALES_REPORT_BY_USER_COMPLETED = 'FETCH_SALES_REPORT_BY_USER_COMPLETED';
export const FETCH_SALES_REPORT_BY_USER_FAILED = 'FETCH_SALES_REPORT_BY_USER_FAILED';

export const FETCH_AVERAGE_SALES_REPORT_STARTED = 'FETCH_AVERAGE_SALES_REPORT_STARTED';
export const FETCH_AVERAGE_SALES_REPORT_COMPLETED = 'FETCH_AVERAGE_SALES_REPORT_COMPLETED';
export const FETCH_AVERAGE_SALES_REPORT_FAILED = 'FETCH_AVERAGE_SALES_REPORT_FAILED';
