export const BRANCH_FETCH_STARTED = 'BRANCH_FETCH_STARTED';
export const BRANCH_FETCH_COMPLETED = 'BRANCH_FETCH_COMPLETED';
export const BRANCH_FETCH_FAILED = 'BRANCH_FETCH_FAILED';

export const BRANCH_ADD_STARTED = 'BRANCH_ADD_STARTED';
export const BRANCH_ADD_COMPLETED = 'BRANCH_ADD_COMPLETED';
export const BRANCH_ADD_FAILED = 'BRANCH_ADD_FAILED';

export const BRANCH_REMOVE_STARTED = 'BRANCH_REMOVE_STARTED';
export const BRANCH_REMOVE_COMPLETED = 'BRANCH_REMOVE_COMPLETED';
export const BRANCH_REMOVE_FAILED = 'BRANCH_REMOVE_FAILED';

export const BRANCH_UPDATE_STARTED = 'BRANCH_UPDATE_STARTED';
export const BRANCH_UPDATE_COMPLETED = 'BRANCH_UPDATE_COMPLETED';
export const BRANCH_UPDATE_FAILED = 'BRANCH_UPDATE_FAILED';

export const BRANCH_SELECTED = 'BRANCH_SELECTED';
export const BRANCH_DESELECTED = 'BRANCH_DESELECTED';