const BRANCH_OFFICE_FETCH_STARTED = 'BRANCH_OFFICE_FETCH_STARTED';
const BRANCH_OFFICE_FETCH_COMPLETED = 'BRANCH_OFFICE_FETCH_COMPLETED';
const BRANCH_OFFICE_FETCH_FAILED = 'BRANCH_OFFICE_FETCH_FAILED';

const BRANCH_OFFICE_ADD_STARTED = 'BRANCH_OFFICE_ADD_STARTED';
const BRANCH_OFFICE_ADD_COMPLETED = 'BRANCH_OFFICE_ADD_COMPLETED';
const BRANCH_OFFICE_ADD_FAILED = 'BRANCH_OFFICE_ADD_FAILED';

const BRANCH_OFFICE_DELETE_STARTED = 'BRANCH_OFFICE_DELETE_STARTED';
const BRANCH_OFFICE_DELETE_COMPLETED = 'BRANCH_OFFICE_DELETE_COMPLETED';
const BRANCH_OFFICE_DELETE_FAILED = 'BRANCH_OFFICE_DELETE_FAILED';

const BRANCH_OFFICE_UPDATE_STARTED = 'BRANCH_OFFICE_UPDATE_STARTED';
const BRANCH_OFFICE_UPDATE_COMPLETED = 'BRANCH_OFFICE_UPDATE_COMPLETED';
const BRANCH_OFFICE_UPDATE_FAILED = 'BRANCH_OFFICE_UPDATE_FAILED';