export const CATEGORIES_FETCH_STARTED = 'CATEGORIES_FETCH_STARTED';
export const CATEGORIES_FETCH_COMPLETED = 'CATEGORIES_FETCH_COMPLETED';
export const CATEGORIES_FETCH_FAILED = 'CATEGORIES_FETCH_FAILED';

export const CATEGORIES_ADD_STARTED = 'CATEGORIES_ADD_STARTED';
export const CATEGORIES_ADD_COMPLETED = 'CATEGORIES_ADD_COMPLETED';
export const CATEGORIES_ADD_FAILED = 'CATEGORIES_ADD_FAILED';

export const CATEGORIES_REMOVE_STARTED = 'CATEGORIES_REMOVE_STARTED';
export const CATEGORIES_REMOVE_COMPLETED = 'CATEGORIES_REMOVE_COMPLETED';
export const CATEGORIES_REMOVE_FAILED = 'CATEGORIES_REMOVE_FAILED';