export const MESEROS_FETCH_STARTED = 'MESERO_FETCH_STARTED';
export const MESEROS_FETCH_COMPLETED = 'MESERO_FETCH_COMPLETED';
export const MESEROS_FETCH_FAILED = 'MESERO_FETCH_FAILED';

export const MESEROS_DELETE_STARTED = 'MESEROS_DELETE_STARTED';
export const MESEROS_DELETE_COMPLETED = 'MESEROS_DELETE_COMPLETED';
export const MESEROS_DELETE_FAILED = 'MESEROS_DELETE_FAILED';